version: "3.9"

services:
  react-app:
    container_name: react_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - snippet
    restart: unless-stopped
networks:
  snippet:
    driver: bridge

